### ISSUE TITLE
Screen headers

### ISSUE THREAD

**Issue by ElbertTse** [KnightHacks/hackathon-app-2021#5]
- This is separate since this component will be shared by all pages
- Should have the screen title with a font color of #2E7AEC (See Figma)
- Should have the light mode, dark mode switch. (Can change this to a button or something later, does not have to work yet).

**Comment by timothyoei** [comment]
For clarity, this issue refers to the screen titles?
![image](https://user-images.githubusercontent.com/37993586/133174577-8ae270ba-07e6-4059-99f3-5702d88b52cd.png)

**Comment by ElbertTse** [comment]
> For clarity, this issue refers to these?
> ![image](https://user-images.githubusercontent.com/37993586/133174577-8ae270ba-07e6-4059-99f3-5702d88b52cd.png)

Yes, we may have to scrap this issue since its kinda already implemented. I'll review what we have now and revise the issues.

**Comment by timothyoei** [comment]
![image](https://user-images.githubusercontent.com/37993586/133468814-e7796b18-c844-4fca-a08e-135ecf4129fc.png)

We could use this issue to change the title's color to the blue used in Figma
