### ISSUE TITLE
Event Countdown

### ISSUE THREAD

**Issue by ElbertTse** [KnightHacks/hackathon-app-2021#6]
- Counts down to hacking end date/time (November 14th, 10AM)
- If date/time is before November 12th at 4:30 PM, swap it to "hacking starts in : HH:MM:SS"
- If date/time is past the end date and time, message should be "Hacking has ended"

**Comment by timothyoei** [comment]
Should we have an in-between message for when hacking has started, but not ended? For example, "hacking ends in HH:MM:SS".

**Comment by suneettipirneni** [comment]
Yeah I think that would be good

**Comment by timothyoei** [comment]
What's the official start time? I remember it being 48 hours, but I could be wrong

**Comment by suneettipirneni** [comment]
Yeah I think it's 48 hours

**Comment by ElbertTse** [comment]
According to the hackathon schedule in notion, its gonna be 48 hours but that's a draft so it might change later. For now, just do 48 hours. And yes if the time is between start and end, we're showing a "hacking ends in HH:MM:SS" message like in Figma
